In [29]:
from pandas import DataFrame

In [30]:
data={'name':['Ebin', 'Alex'],
     'age':[25,64],
     'salary' : [25, 10]}

In [31]:
frame=DataFrame(data)
frame

   name  age  salary
0  Ebin   25      25
1  Alex   64      10

In [32]:
newframe=DataFrame(data, columns=['name','salary', 'age'])
newframe

   name  salary  age
0  Ebin      25   25
1  Alex      10   64

In [33]:
newframe.loc[1]

name      Alex
salary      10
age         64
Name: 1, dtype: object

In [34]:
newframe['profile']='IT', 'tailor'
newframe['edu']='BCA', '10'
newframe

   name  salary  age profile  edu
0  Ebin      25   25      IT  BCA
1  Alex      10   64  tailor   10

In [35]:
newframe.drop('edu', axis=1, inplace=True)

In [36]:
newframe.loc[len(newframe)] = ["Stella Alex", 35, 50, "House Wife"]

In [37]:
newframe

          name  salary  age     profile
0         Ebin      25   25          IT
1         Alex      10   64      tailor
2  Stella Alex      35   50  House Wife

In [38]:
newframe

          name  salary  age     profile
0         Ebin      25   25          IT
1         Alex      10   64      tailor
2  Stella Alex      35   50  House Wife

In [39]:
from pandas import Series
obj=Series([1,2,3], index=['a','b','c'])

In [40]:
obj

a    1
b    2
c    3
dtype: int64

In [41]:
obj=obj.reindex(['a','c','b'])

In [42]:
obj

a    1
c    3
b    2
dtype: int64