In [1]:
from pandas import Series
ser=Series([30,36,100], index=['speed','temp', 'humidity'])
ser

speed        30
temp         36
humidity    100
dtype: int64

In [2]:
from pandas import DataFrame 
data={'speed':[35,38],'temp':[25,26],'humidity':[110,105]}
frame=DataFrame(data)
frame

   speed  temp  humidity
0     35    25       110
1     38    26       105

In [3]:
ser + frame, ser- frame

(   speed  temp  humidity
 0     65    61       210
 1     68    62       205,
    speed  temp  humidity
 0     -5    11       -10
 1     -8    10        -5)

In [4]:
frame.sort_index()

   speed  temp  humidity
0     35    25       110
1     38    26       105

In [5]:
frame.sort_index(axis=0)

   speed  temp  humidity
0     35    25       110
1     38    26       105

In [6]:
frame.sort_values(by='humidity')

   speed  temp  humidity
1     38    26       105
0     35    25       110