In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
#The below url contains html tables with data about world population.
url = "https://en.wikipedia.org/wiki/World_population"
# get the contents of the webpage in text format and store in a variable called data
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                  "AppleWebKit/537.36 (KHTML, like Gecko) "
                  "Chrome/91.0.4472.124 Safari/537.36"
}

data  = requests.get(url, headers=headers)
soup = BeautifulSoup(data.text,"html.parser")

In [2]:
#find all html tables in the web page
tables = soup.find_all('table') # in html table is represented by the tag <table>
# we can see how many tables were found by checking the length of the tables list
len(tables)

27

In [3]:
for index,table in enumerate(tables):
    if ("10 most densely populated countries" in str(table)):
        table_index = index
print(table_index)
print(tables[table_index].prettify())

5
<table class="wikitable sortable" id="mwBLk" style="text-align:right">
 <caption id="mwBLo">
  10 most densely populated countries
  <small id="mwBLs">
   (with population above 5
   <span id="mwBLw" typeof="mw:Entity">
   </span>
   million)
  </small>
  <sup about="#mwt478" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":":10"},"body":{"id":"mw-reference-text-cite_note-:10-106"}}' id="cite_ref-:10_106-0" rel="dc:references" typeof="mw:Extension/ref">
   <a href="#cite_note-:10-106" id="mwBL0">
    <span class="mw-reflink-text" id="mwBL4">
     <span class="cite-bracket" id="mwBL8">
      [
     </span>
     101
     <span class="cite-bracket" id="mwBMA">
      ]
     </span>
    </span>
   </a>
  </sup>
 </caption>
 <tbody id="mwBME">
  <tr id="mwBMI">
   <th id="mwBMM" scope="col">
    Rank
   </th>
   <th id="mwBMQ" scope="col">
    Country
   </th>
   <th id="mwBMU" scope="col">
    Population
   </th>
   <th id="mwBMY" scope="col">
    Area
    <br id="mwBMc"/>
    <small id="mwBMg">
     (km
     <sup id="mwBMk">
      2
     </sup>
     )
    </small>
   </th>
   <th id="mwBMo" scope="col">
    Density
    <br id="mwBMs"/>
    <small id="mwBMw">
     (pop/km
     <sup id="mwBM0">
      2
     </sup>
     )
    </small>
   </th>
  </tr>
  <tr id="mwBM4">
   <td id="mwBM8">
    1
   </td>
   <td align="left" id="mwBNA">
    <span about="#mwt479" class="flagicon nowrap" data-mw='{"parts":[{"template":{"target":{"wt":"Flag","href":"./Template:Flag"},"params":{"1":{"wt":"Singapore"}},"i":0}}]}' id="mwBNE" typeof="mw:Transclusion">
     <span class="mw-image-border" typeof="mw:File">
      <span>
       <img alt="" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="900" decoding="async" height="15" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Flag_of_Singapore.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/40px-Flag_of_Singapore.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/60px-Flag_of_Singapore.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/>
      </span>
     </span>
    </span>
    <a about="#mwt479" href="https://en.wikipedia.org/wiki/Singapore" id="mwBNI" rel="mw:WikiLink" title="Singapore">
     Singapore
    </a>
   </td>
   <td id="mwBNM">
    5,921,231
   </td>
   <td id="mwBNQ">
    719
   </td>
   <td id="mwBNU">
    8,235
   </td>
  </tr>
  <tr id="mwBNY">
   <td id="mwBNc">
    2
   </td>
   <td align="left" id="mwBNg">
    <span about="#mwt480" class="flagicon nowrap" data-mw='{"parts":[{"template":{"target":{"wt":"Flag","href":"./Template:Flag"},"params":{"1":{"wt":"Bangladesh"}},"i":0}}]}' id="mwBNk" typeof="mw:Transclusion">
     <span class="mw-image-border" typeof="mw:File">
      <span>
       <img alt="" class="mw-file-element" data-file-height="307" data-file-type="drawing" data-file-width="512" decoding="async" height="14" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Flag_of_Bangladesh.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/40px-Flag_of_Bangladesh.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/60px-Flag_of_Bangladesh.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/>
      </span>
     </span>
    </span>
    <a about="#mwt480" href="https://en.wikipedia.org/wiki/Bangladesh" id="mwBNo" rel="mw:WikiLink" title="Bangladesh">
     Bangladesh
    </a>
   </td>
   <td id="mwBNs">
    165,650,475
   </td>
   <td id="mwBNw">
    148,460
   </td>
   <td id="mwBN0">
    1,116
   </td>
  </tr>
  <tr id="mwBN4">
   <td id="mwBN8">
    3
   </td>
   <td align="left" id="mwBOA">
    <p id="mwBOE">
     <span about="#mwt481" class="flagicon nowrap" data-mw='{"parts":[{"template":{"target":{"wt":"Flag","href":"./Template:Flag"},"params":{"1":{"wt":"Palestine"}},"i":0}}]}' id="mwBOI" typeof="mw:Transclusion">
      <span class="mw-image-border" typeof="mw:File">
       <span>
        <img alt="" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="1200" decoding="async" height="12" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Flag_of_Palestine.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Palestine.svg/40px-Flag_of_Palestine.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Palestine.svg/60px-Flag_of_Palestine.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/>
       </span>
      </span>
     </span>
     <a about="#mwt481" href="https://en.wikipedia.org/wiki/Palestine" id="mwBOM" rel="mw:WikiLink" title="Palestine">
      Palestine
     </a>
     <sup about="#mwt482" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"group":"note"},"body":{"id":"mw-reference-text-cite_note-107"}}' id="cite_ref-107" rel="dc:references" typeof="mw:Extension/ref">
      <a data-mw-group="note" href="#cite_note-107" id="mwBOQ">
       <span class="mw-reflink-text" id="mwBOU">
        <span class="cite-bracket" id="mwBOY">
         [
        </span>
        note 3
        <span class="cite-bracket" id="mwBOc">
         ]
        </span>
       </span>
      </a>
     </sup>
     <sup about="#mwt485" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-108"}}' id="cite_ref-108" rel="dc:references" typeof="mw:Extension/ref">
      <a href="#cite_note-108" id="mwBOg">
       <span class="mw-reflink-text" id="mwBOk">
        <span class="cite-bracket" id="mwBOo">
         [
        </span>
        102
        <span class="cite-bracket" id="mwBOs">
         ]
        </span>
       </span>
      </a>
     </sup>
    </p>
   </td>
   <td id="mwBOw">
    5,223,000
   </td>
   <td id="mwBO0">
    6,025
   </td>
   <td id="mwBO4">
    867
   </td>
  </tr>
  <tr id="mwBO8">
   <td id="mwBPA">
    4
   </td>
   <td align="left" id="mwBPE">
    <span about="#mwt486" class="flagicon nowrap" data-mw='{"parts":[{"template":{"target":{"wt":"Flag","href":"./Template:Flag"},"params":{"1":{"wt":"Taiwan"}},"i":0}}]}' id="mwBPI" typeof="mw:Transclusion">
     <span class="mw-image-border" typeof="mw:File">
      <span>
       <img alt="" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="900" decoding="async" height="15" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Flag_of_the_Republic_of_China.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/40px-Flag_of_the_Republic_of_China.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/60px-Flag_of_the_Republic_of_China.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/>
      </span>
     </span>
    </span>
    <a about="#mwt486" href="https://en.wikipedia.org/wiki/Taiwan" id="mwBPM" rel="mw:WikiLink" title="Taiwan">
     Taiwan
    </a>
    <sup about="#mwt487" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"group":"note"},"body":{"id":"mw-reference-text-cite_note-109"}}' id="cite_ref-109" rel="dc:references" typeof="mw:Extension/ref">
     <a data-mw-group="note" href="#cite_note-109" id="mwBPQ">
      <span class="mw-reflink-text" id="mwBPU">
       <span class="cite-bracket" id="mwBPY">
        [
       </span>
       note 4
       <span class="cite-bracket" id="mwBPc">
        ]
       </span>
      </span>
     </a>
    </sup>
   </td>
   <td id="mwBPg">
    23,580,712
   </td>
   <td id="mwBPk">
    35,980
   </td>
   <td id="mwBPo">
    655
   </td>
  </tr>
  <tr id="mwBPs">
   <td id="mwBPw">
    5
   </td>
   <td align="left" id="mwBP0">
    <span about="#mwt488" class="flagicon nowrap" data-mw='{"parts":[{"template":{"target":{"wt":"Flag","href":"./Template:Flag"},"params":{"1":{"wt":"South Korea"}},"i":0}}]}' id="mwBP4" typeof="mw:Transclusion">
     <span class="mw-image-border" typeof="mw:File">
      <span>
       <img alt="" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="900" decoding="async" height="15" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Flag_of_South_Korea.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/40px-Flag_of_South_Korea.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/60px-Flag_of_South_Korea.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/>
      </span>
     </span>
    </span>
    <a about="#mwt488" href="https://en.wikipedia.org/wiki/South_Korea" id="mwBP8" rel="mw:WikiLink" title="South Korea">
     South Korea
    </a>
   </td>
   <td id="mwBQA">
    51,844,834
   </td>
   <td id="mwBQE">
    99,720
   </td>
   <td id="mwBQI">
    520
   </td>
  </tr>
  <tr id="mwBQM">
   <td id="mwBQQ">
    6
   </td>
   <td align="left" id="mwBQU">
    <span about="#mwt489" class="flagicon nowrap" data-mw='{"parts":[{"template":{"target":{"wt":"Flag","href":"./Template:Flag"},"params":{"1":{"wt":"Lebanon"}},"i":0}}]}' id="mwBQY" typeof="mw:Transclusion">
     <span class="mw-image-border" typeof="mw:File">
      <span>
       <img alt="" class="mw-file-element" data-file-height="1920" data-file-type="drawing" data-file-width="2880" decoding="async" height="15" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Flag_of_Lebanon.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/5/59/Flag_of_Lebanon.svg/40px-Flag_of_Lebanon.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/5/59/Flag_of_Lebanon.svg/60px-Flag_of_Lebanon.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/>
      </span>
     </span>
    </span>
    <a about="#mwt489" href="https://en.wikipedia.org/wiki/Lebanon" id="mwBQc" rel="mw:WikiLink" title="Lebanon">
     Lebanon
    </a>
   </td>
   <td id="mwBQg">
    5,296,814
   </td>
   <td id="mwBQk">
    10,400
   </td>
   <td id="mwBQo">
    509
   </td>
  </tr>
  <tr id="mwBQs">
   <td id="mwBQw">
    7
   </td>
   <td align="left" id="mwBQ0">
    <span about="#mwt490" class="flagicon nowrap" data-mw='{"parts":[{"template":{"target":{"wt":"Flag","href":"./Template:Flag"},"params":{"1":{"wt":"Rwanda"}},"i":0}}]}' id="mwBQ4" typeof="mw:Transclusion">
     <span class="mw-image-border" typeof="mw:File">
      <span>
       <img alt="" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="900" decoding="async" height="15" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Flag_of_Rwanda.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Rwanda.svg/40px-Flag_of_Rwanda.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Rwanda.svg/60px-Flag_of_Rwanda.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/>
      </span>
     </span>
    </span>
    <a about="#mwt490" href="https://en.wikipedia.org/wiki/Rwanda" id="mwBQ8" rel="mw:WikiLink" title="Rwanda">
     Rwanda
    </a>
   </td>
   <td id="mwBRA">
    13,173,730
   </td>
   <td id="mwBRE">
    26,338
   </td>
   <td id="mwBRI">
    500
   </td>
  </tr>
  <tr id="mwBRM">
   <td id="mwBRQ">
    8
   </td>
   <td align="left" id="mwBRU">
    <span about="#mwt491" class="flagicon nowrap" data-mw='{"parts":[{"template":{"target":{"wt":"Flag","href":"./Template:Flag"},"params":{"1":{"wt":"Burundi"}},"i":0}}]}' id="mwBRY" typeof="mw:Transclusion">
     <span class="mw-image-border" typeof="mw:File">
      <span>
       <img alt="" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="1000" decoding="async" height="14" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Flag_of_Burundi.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Burundi.svg/40px-Flag_of_Burundi.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Burundi.svg/60px-Flag_of_Burundi.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/>
      </span>
     </span>
    </span>
    <a about="#mwt491" href="https://en.wikipedia.org/wiki/Burundi" id="mwBRc" rel="mw:WikiLink" title="Burundi">
     Burundi
    </a>
   </td>
   <td id="mwBRg">
    12,696,478
   </td>
   <td id="mwBRk">
    27,830
   </td>
   <td id="mwBRo">
    456
   </td>
  </tr>
  <tr id="mwBRs">
   <td id="mwBRw">
    9
   </td>
   <td align="left" id="mwBR0">
    <span about="#mwt492" class="flagicon nowrap" data-mw='{"parts":[{"template":{"target":{"wt":"Flag","href":"./Template:Flag"},"params":{"1":{"wt":"Israel"}},"i":0}}]}' id="mwBR4" typeof="mw:Transclusion">
     <span class="mw-image-border" typeof="mw:File">
      <span>
       <img alt="" class="mw-file-element" data-file-height="800" data-file-type="drawing" data-file-width="1100" decoding="async" height="15" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Flag_of_Israel.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Israel.svg/40px-Flag_of_Israel.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Israel.svg/60px-Flag_of_Israel.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="21"/>
      </span>
     </span>
    </span>
    <a about="#mwt492" href="https://en.wikipedia.org/wiki/Israel" id="mwBR8" rel="mw:WikiLink" title="Israel">
     Israel
    </a>
   </td>
   <td id="mwBSA">
    9,402,617
   </td>
   <td id="mwBSE">
    21,937
   </td>
   <td id="mwBSI">
    429
   </td>
  </tr>
  <tr id="mwBSM">
   <td id="mwBSQ">
    10
   </td>
   <td align="left" id="mwBSU">
    <span about="#mwt493" class="flagicon nowrap" data-mw='{"parts":[{"template":{"target":{"wt":"Flag","href":"./Template:Flag"},"params":{"1":{"wt":"India"}},"i":0}}]}' id="mwBSY" typeof="mw:Transclusion">
     <span class="mw-image-border" typeof="mw:File">
      <span>
       <img alt="" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="900" decoding="async" height="15" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Flag_of_India.svg" src="//upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/40px-Flag_of_India.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/60px-Flag_of_India.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/>
      </span>
     </span>
    </span>
    <a about="#mwt493" href="https://en.wikipedia.org/wiki/India" id="mwBSc" rel="mw:WikiLink" title="India">
     India
    </a>
   </td>
   <td id="mwBSg">
    1,389,637,446
   </td>
   <td id="mwBSk">
    3,287,263
   </td>
   <td id="mwBSo">
    423
   </td>
  </tr>
 </tbody>
</table>

In [4]:
population_data = pd.DataFrame(columns=["Rank", "Country", "Population", "Area", "Density"])

for row in tables[table_index].tbody.find_all("tr"):
    col = row.find_all("td")
    if col:
        rank = col[0].text.strip()
        country = col[1].text.strip()
        population = col[2].text.strip()
        area = col[3].text.strip()
        density = col[4].text.strip()

        # Create a temporary DataFrame for the new row
        new_row = pd.DataFrame([{"Rank": rank, "Country": country, "Population": population, "Area": area, "Density": density}])

        # Use concat 
        population_data = pd.concat([population_data, new_row], ignore_index=True)

population_data

  Rank                 Country     Population       Area Density
0    1               Singapore      5,921,231        719   8,235
1    2              Bangladesh    165,650,475    148,460   1,116
2    3  Palestine[note 3][102]      5,223,000      6,025     867
3    4          Taiwan[note 4]     23,580,712     35,980     655
4    5             South Korea     51,844,834     99,720     520
5    6                 Lebanon      5,296,814     10,400     509
6    7                  Rwanda     13,173,730     26,338     500
7    8                 Burundi     12,696,478     27,830     456
8    9                  Israel      9,402,617     21,937     429
9   10                   India  1,389,637,446  3,287,263     423

In [8]:
from io import StringIO
pd.read_html(StringIO(str(tables[5])), flavor='bs4')
population_data_read_html = pd.read_html(StringIO(str(tables[5])), flavor='bs4')[0]

population_data_read_html

   Rank                 Country  Population  Area (km2)  Density (pop/km2)
0     1               Singapore     5921231         719               8235
1     2              Bangladesh   165650475      148460               1116
2     3  Palestine[note 3][102]     5223000        6025                867
3     4          Taiwan[note 4]    23580712       35980                655
4     5             South Korea    51844834       99720                520
5     6                 Lebanon     5296814       10400                509
6     7                  Rwanda    13173730       26338                500
7     8                 Burundi    12696478       27830                456
8     9                  Israel     9402617       21937                429
9    10                   India  1389637446     3287263                423

In [9]:
dataframe_list = pd.read_html(StringIO(data.text), flavor='bs4')
len(dataframe_list)
dataframe_list[5]
heading = soup.find("h3", {"id": "Most_densely_populated_countries"})

# Get the next table after this heading
table = heading.find_next("table")

# Convert to DataFrame
df = pd.read_html(StringIO(str(table)))[0]
print(df.head())

   Rank                 Country  Population  Area (km2)  Density (pop/km2)
0     1               Singapore     5921231         719               8235
1     2              Bangladesh   165650475      148460               1116
2     3  Palestine[note 3][102]     5223000        6025                867
3     4          Taiwan[note 4]    23580712       35980                655
4     5             South Korea    51844834       99720                520